Repository ecsite-project/ec-202404b-back, pull requests merged in 2024-06, with the labels that each got.

#6 Feature/use data jpa
  build.gradle
  src/main/java/com/example/contoroller/AuthenticationController.java
  src/main/java/com/example/domain/Item.java
  src/main/java/com/example/domain/Option.java
  src/main/java/com/example/domain/OptionGroup.java
  src/main/java/com/example/domain/Order.java
  src/main/java/com/example/domain/OrderItem.java
  src/main/java/com/example/domain/User.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#8 docs: ddlの編集
  document/myddl.sql
Labels: bug, documentation

#9 docs: ddlの編集2
  document/myddl.sql
Labels: bug, documentation

#10 bugfix: itemテーブルにbirth_day列が抜けてました
  document/myddl.sql
Labels: bug, documentation

#11 ユーザー登録機能
  document/CreateUserService-test-doc.txt
  src/main/java/com/example/contoroller/CreateUserContoroller.java
  src/main/java/com/example/contoroller/CreateUserController.java
  src/main/java/com/example/domain/User.java
  src/main/java/com/example/dtos/UserRegistrationDto.java
  src/main/java/com/example/repositories/UserRepository.java
  src/main/java/com/example/security/SecurityConfig.java
  src/main/java/com/example/service/CreateUserService.java
Labels: enhancement

#26 画像をローカルのストレージで管理するように
  images/cat1.jpg
  images/cat2.jpg
  images/cat3.jpg
  images/cat4.jpg
  images/cat5.jpeg
  images/dog1.jpg
  images/dog2.jpg
  images/dog3.jpg
  images/dog4.jpg
  images/dog5.jpg
  src/main/java/com/example/contoroller/SourceController.java
  src/main/java/com/example/service/ImageService.java
Labels: enhancement

#39 クレジットカード機能
  build.gradle
  src/main/java/com/example/configuration/Config.java
  src/main/java/com/example/dtos/CreditCardAPIResponseDTO.java
  src/main/java/com/example/dtos/PaymentInfoDTO.java
  src/main/java/com/example/service/CreditCardService.java
Labels: enhancement

#47 ページング機能実装
  src/main/java/com/example/DataInitializer.java
  src/main/java/com/example/contoroller/ShowItemListController.java
  src/main/java/com/example/dtos/PageRequestDto.java
  src/main/java/com/example/dtos/PageResponseDto.java
  src/main/java/com/example/dtos/SearchDto.java
  src/main/java/com/example/repository/ItemRepository.java
  src/main/java/com/example/service/ShowItemListService.java
Labels: enhancement

#46 DBが毎回初期化されないように
  src/main/java/com/example/DataInitializer.java
  src/main/resources/application.yml
Labels: bug

#50 メールアドレス重複時にvalidationエラーを返すように
  src/main/java/com/example/contoroller/CreateUserController.java
Labels: enhancement

#55 カートのオプションを表示できるように修正した。
  src/main/java/com/example/DataInitializer.java
  src/main/java/com/example/domain/Option.java
  src/main/java/com/example/domain/OrderItem.java
  src/main/java/com/example/repository/OptionRepository.java
  src/main/resources/application.yml
Labels: bug

#57 クエリパラメータで受け取れるように
  src/main/java/com/example/contoroller/ShowItemDetailController.java
Labels: bug

#59 SQLのデータを増やしました
  images/abyssinian.jpg
  images/beagle.jpg
  images/bengal.jpg
  images/bulldog.jpg
  images/cat1.jpg
  images/cat2.jpg
  images/cat3.jpg
  images/cat4.jpg
  images/cat5.jpeg
  images/chihuahua.jpg
  images/dachshund.jpg
  images/dog1.jpg
  images/dog2.jpg
  images/dog3.jpg
  images/dog4.jpg
  images/dog5.jpg
  images/german_shepherd.jpg
  images/golden_retriever.jpg
  images/labrador.jpg
  images/mainecoon.jpg
  images/nekomeme.jpg
  images/norwegianforestcat.jpg
  images/persian.jpg
  images/poodle.jpg
  images/russianblue.jpg
  images/scottishfold.jpg
  images/shiba_inu.jpg
  images/siamese.jpg
  images/sphynx.jpg
  src/main/java/com/example/DataInitializer.java
  src/main/resources/application.yml
Labels: bug, documentation

#60 注文完了まで行えるように
  src/main/java/com/example/contoroller/FinalizeOrderController.java
  src/main/java/com/example/contoroller/UserInfoController.java
  src/main/java/com/example/dtos/UserInfo.java
  src/main/java/com/example/repository/OrderRepository.java
  src/main/java/com/example/security/JWTAuthenticationToken.java
  src/main/java/com/example/service/ShoppingCartService.java
  src/main/java/com/example/service/UserInfoService.java
Labels: enhancement

#61 Mail service
  build.gradle
  src/main/java/com/example/contoroller/MailController.java
  src/main/java/com/example/repository/OrderRepository.java
  src/main/java/com/example/service/MailService.java
  src/main/resources/application.yml
Labels: enhancement

#65 メール送信が行われるように
  src/main/java/com/example/contoroller/FinalizeOrderController.java
  src/main/java/com/example/service/FinalizeOrderService.java
Labels: enhancement

#66 fix: ユーザー情報取得時にセキュリティを考慮するように
  src/main/java/com/example/contoroller/UserInfoController.java
Labels: bug

#67 ログイン時にカートの情報を引き継ぐように
  src/main/java/com/example/contoroller/AuthenticationController.java
  src/main/java/com/example/dtos/LoginDto.java
  src/main/java/com/example/service/AuthenticationService.java
  src/main/java/com/example/service/ShoppingCartService.java
Labels: enhancement

#64 sold out機能の追加
  document/楽楽ペット チームB成果発表.pptx
  src/main/java/com/example/DataInitializer.java
  src/main/java/com/example/service/FinalizeOrderService.java
  src/main/java/com/example/service/MailService.java
  src/main/java/com/example/service/ShoppingCartService.java
Labels: enhancement

#68 非同期メール
  src/main/java/com/example/configuration/AsyncConfig.java
  src/main/java/com/example/configuration/Config.java
  src/main/java/com/example/configuration/MailTask.java
  src/main/java/com/example/contoroller/FinalizeOrderController.java
  src/main/java/com/example/contoroller/MailController.java
  src/main/java/com/example/service/AsyncMail.java
  src/main/java/com/example/service/MailService.java
Labels: enhancement

#69 メールにおいて、金額表示をカンマ区切りに変更、円（単位）の追加
  src/main/java/com/example/service/MailService.java
Labels: bug
